apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Spring-Observability-Kotlin
  annotations:
    github.com/project-slug: rahulUpswing/Spring-Observability-Kotlin
spec:
  type: other
  lifecycle: unknown
